### ISSUE TITLE
"COPD, exacerbation" vs "COPD, exacerbated"

### ISSUE THREAD

**Issue by mcjustin** [uwcirg/carl#15]
Per the [CNICS Dx Code  Med Code for Heidi with COPD highlighted in blue.2021-08-31 spreadsheet](https://docs.google.com/spreadsheets/d/1LZqUB4SDpK1Uu-ZyNcwCkr-6owoMM0aqxfhxjM8qoe0/edit#gid=1264676875), the codes for COPD are `COPD` and `COPD, exacerbation`. However, we have referred to the long version as `COPD, exacerbated` in the past, and I see this in CARL instead of the one we actually want. This is a code in that file (alongside what look like normal ICD codes), but I don't see either of these two in carl ( https://github.com/uwcirg/carl/blob/develop/carl/serialized/COPD_valueset.json#L42 ). I don't know if they're actually used as codes in the source data, but we should add the `COPD, exacerbation` code and correct references to `COPD, exacerbated`.

**Comment by mcjustin** [comment]
@jsibley  I meant to raise this on the call today, just FYI. https://github.com/uwcirg/cnics-to-fhir ignores this level of detail, as I read it.

**Comment by jsibley** [comment]
@mcjustin Confirmed, the "CNICS Standard" codes are `COPD` and `COPD, exacerbation`.

**Comment by pbugni** [comment]
@mcjustin is there outstanding work for `carl` here? 

Looking up ICD 9 code for:
```
COPD with exacerbation is classified to code 491.21, which also includes the following:

    Acute Exacerbation of COPD
    Exacerbation of COPD
    Decompensated COPD
    Decompensated COPD with Exacerbation
    COPD in Exacerbation
    Severe COPD in exacerbation
    End-stage COPD in exacerbation
```
We do include [ICD 9 491.21](https://github.com/uwcirg/carl/blob/develop/carl/serialized/COPD_valueset.json#L64) as currently part of the "COPD value set".

**Comment by mcjustin** [comment]
@pbugni I'd just replace the 3 references in carl from `COPD exacerbated` to `COPD, exacerbation`. As I read it, the string is not used computationally, it's only in valueset description. So not urgent, but just for consistency.

**Comment by pbugni** [comment]
Of course, let's correct to match.  See PR https://github.com/uwcirg/carl/pull/17
